name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  repository:
    description: The quay.io repository in the form OWNER/IMAGE
    required: true
    default: ''
  version:
    description: The new application version, must be semver (MAJOR.MINOR.PATCH)
    required: true
    default: ''

# Define your outputs here.
outputs:
  buildNumber:
    description:
      The build number to use for the next image tag
      (MAJOR.MINOR.PATCH-buildNumber)

runs:
  using: node20
  main: dist/index.js
