name: Continuous Integration

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-test
        run: npm run test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          repository: jupyterhub/jupyterhub
          # This is an old release, so won't be updated
          version: '5.2.0'

      - name: Check Output
        id: output
        run: |
          if [ "${{ steps.test-action.outputs.tags }}" != "[]" ]; then
            echo "ERROR: ${{ steps.test-action.outputs.tags }} != []"
            exit 1
          fi
          if [ "${{ steps.test-action.outputs.buildNumber }}" != "0" ]; then
            echo "ERROR: ${{ steps.test-action.outputs.buildNumber }} != 0"
            exit 1
          fi
